export type Lang = "en" | "ar";
export type ProjectType = "design" | "development" | "landing" | "maintenance";

export const copy = {
  en: {
    skip: "Skip to content",
    scroll: "Scroll",
    nav: {
      work: "Work",
      services: "Services",
      about: "About",
      contact: "Contact",
      menu: "Menu",
      close: "Close",
    },
    hero: {
      kicker: "Digital agency for higher standards",
      title: "ALTURA",
      line: "Digital experiences,\nraised.",
      lead: "ALTURA designs and engineers websites and digital experiences that raise how a business is seen, used, and trusted. Strategy, design, and engineering — held to a higher standard.",
      primary: "Start a project",
      secondary: "See the work",
      roles: ["Strategy", "Design", "Engineering", "Intelligence"],
    },
    work: {
      index: "01",
      label: "Selected work",
      title: "A product, built\nas a platform.",
      lead: "Featured engagement — architecture, interface, and engineering, treated as one system.",
      visit: "Visit the live product",
      featured: {
        id: "open",
        name: "open",
        category: "Digital product & platform",
        header: "open — Product and platform, engineered together.",
        subheading: "A high-performance web experience, built to grow with the company.",
        story:
          "We partnered with open to turn an ambitious product vision into a complete digital platform. Architecture, interface, and engineering moved as one system — so the brand, the performance, and the product arrived together.",
        badges: [
          "Product Strategy",
          "Interface Engineering",
          "Full-Stack Development",
          "Performance Systems",
        ],
        website: "https://www.open.cx",
        websiteLabel: "open.cx",
        video: "/work/open-re.mp4",
        poster: "/work/oben-desktop.png",
        videoAlt: "Screen recording of the open website in a browser frame.",
      },
      testimonial: {
        quote:
          "Working with the team was an exceptional experience. They demonstrated world-class standards in product engineering, rapid execution, and the ability to translate complex business needs into an intuitive digital product. I highly recommend them to anyone looking to build a top-tier digital product.",
        name: "Mohammad Gharabat",
        role: "Founder & CEO at open",
        initials: "MG",
        photo: "/work/mohammad-gharabat.jpg",
        contact: "Ask the founder",
        linkedInLabel: "LinkedIn",
        emailLabel: "Email",
        linkedIn: "https://www.linkedin.com/in/gharabat",
        email: "mo@open.cx",
      },
    },
    services: {
      index: "02",
      label: "Services",
      title: "What we raise.",
      items: [
        {
          n: "01",
          title: "Web Design",
          body: "Interfaces with a point of view. We design structure, type, and behavior so the brand feels considered on every screen — not adapted after the fact.",
        },
        {
          n: "02",
          title: "Web Development",
          body: "The design, built as a product. Fast, durable engineering with room to grow — not a theme with the logo swapped.",
        },
        {
          n: "03",
          title: "Landing Pages",
          body: "A single surface with a single job. Focused, quick to grasp, and written to convert — nothing ornamental, nothing extra.",
        },
        {
          n: "04",
          title: "After Launch",
          body: "The product does not freeze on ship day. Updates, refinements, and reliability so the experience stays sharp as the business moves.",
        },
      ],
    },
    about: {
      index: "03",
      label: "About",
      name: "ALTURA",
      aside: "Digital agency · Elevation through craft",
      title: "ALTURA exists to raise how a business is experienced online.",
      p1: "We combine strategy, design, engineering, and human creativity. Modern technology — including AI — sits inside the workflow: research, exploration, production. The point is not a louder site. It is a higher standard of presence.",
      p2: "The collaboration is direct. You speak with the people making the product. Decisions stay close. The work is made to represent a business — local or international — and to help people hire you or buy from you.",
      p3: "We are a lean studio. There is no account layer. If the work is ours to make, we make it. Then we stay with it — testing, refining, raising the experience as the business grows.",
    },
    process: {
      index: "04",
      label: "Process",
      title: "Work that keeps rising.",
      steps: [
        {
          n: "01",
          title: "Understand",
          body: "We study the business, the audience, and the constraint. We question the brief before we honor it. No work starts without that.",
        },
        {
          n: "02",
          title: "Shape",
          body: "Strategy becomes a concept. Type, interface, and system — until the product feels inevitable, not assembled.",
        },
        {
          n: "03",
          title: "Build",
          body: "We engineer for speed, clarity, and durability. Intelligent tools sit inside the workflow, so the work moves further without losing care.",
        },
        {
          n: "04",
          title: "Evolve",
          body: "Launch is a beginning. We test, refine, and keep raising the product as the business changes.",
        },
      ],
    },
    why: {
      index: "05",
      label: "Why ALTURA",
      title: "Higher standards.\nClearer execution.",
      items: [
        {
          n: "01",
          title: "The people making it.",
          body: "You work with the designers and engineers on the product. No account layer between you and the work.",
        },
        {
          n: "02",
          title: "One system, not a handoff.",
          body: "Design, engineering, and modern AI-powered workflows stay in the same conversation. Nothing is lost between the idea and the build.",
        },
        {
          n: "03",
          title: "Built to perform.",
          body: "The site has a job: represent the company, earn trust, and convert. We design for that — then keep raising it.",
        },
      ],
    },
    contact: {
      index: "06",
      label: "Contact",
      title: "Ready to rise.\nStart here.",
      lead: "Tell us what the business does, whether a site exists, and any timing that matters. We read every brief.",
      book: "Work with ALTURA",
      bookNote: "Or send a brief below.",
      bookModalTitle: "A conversation",
      bookModalLead: "Thirty minutes. The business, the product, and whether we should work together.",
      bookModalCta: "Email to schedule",
      bookClose: "Close",
      name: "Name",
      email: "Email",
      type: "Where should we begin?",
      types: {
        design: "Web design",
        development: "Web development",
        landing: "Landing page",
        maintenance: "After launch",
      },
      message: "Message",
      submit: "Send the brief",
      sending: "Sending",
      successTitle: "It's with us.",
      successBody: "We read every brief. You'll hear back by email.",
      another: "Send another",
      errors: {
        name: "Please add your name.",
        email: "Please add a valid email.",
        type: "Please choose where we should begin.",
        message: "Please add a short note about the project.",
      },
    },
    footer: {
      email: "hello@altura.com",
      line: "Digital experiences, raised.",
    },
  },
  ar: {
    skip: "تخطي إلى المحتوى",
    scroll: "تمرير",
    nav: {
      work: "الأعمال",
      services: "الخدمات",
      about: "نبذة",
      contact: "تواصل",
      menu: "القائمة",
      close: "إغلاق",
    },
    hero: {
      kicker: "وكالة رقمية بمعايير أعلى",
      title: "ALTURA",
      line: "تجارب رقمية،\nمرفوعة.",
      lead: "ALTURA تصمّم وتهندس مواقع وتجارب رقمية ترفع طريقة رؤية العمل واستخدامه والثقة به. استراتيجية وتصميم وهندسة — بمعيار أعلى.",
      primary: "ابدأ مشروعاً",
      secondary: "شاهد العمل",
      roles: ["استراتيجية", "تصميم", "هندسة", "ذكاء"],
    },
    work: {
      index: "01",
      label: "أعمال مختارة",
      title: "منتج يُبنى\nكمنصة.",
      lead: "عمل مختار — هندسة المنتج والواجهة والتطوير، كنظام واحد.",
      visit: "زيارة المنتج الحي",
      featured: {
        id: "open",
        name: "أوبن",
        category: "منتج رقمي ومنصة",
        header: "أوبن — منتج ومنصة، يُهندسان معاً.",
        subheading: "تجربة ويب عالية الأداء، مبنية لتنمو مع الشركة.",
        story:
          "شاركنا أوبن في تحويل رؤية منتج طموحة إلى منصة رقمية مكتملة. تحركت الهندسة والواجهة والتطوير كنظام واحد — فوصلت العلامة والأداء والمنتج معاً.",
        badges: ["استراتيجية المنتج", "هندسة الواجهة", "تطوير كامل", "أنظمة الأداء"],
        website: "https://www.open.cx",
        websiteLabel: "open.cx",
        video: "/work/open-re.mp4",
        poster: "/work/oben-desktop.png",
        videoAlt: "تسجيل لشاشة موقع أوبن داخل إطار متصفح.",
      },
      testimonial: {
        quote:
          "العمل مع الفريق كان تجربة استثنائية. أظهروا معايير عالمية في هندسة المنتج، وتنفيذاً سريعاً، وقدرة على تحويل احتياجات العمل المعقّدة إلى منتج رقمي بديهي. أوصي بهم بقوة لكل من يريد بناء منتج رقمي من الطراز الأول.",
        name: "محمد غرابات",
        role: "مؤسس والرئيس التنفيذي في أوبن",
        initials: "مغ",
        photo: "/work/mohammad-gharabat.jpg",
        contact: "اسأل المؤسس",
        linkedInLabel: "لينكدإن",
        emailLabel: "البريد",
        linkedIn: "https://www.linkedin.com/in/gharabat",
        email: "mo@open.cx",
      },
    },
    services: {
      index: "02",
      label: "خدمات",
      title: "ما نرفعه.",
      items: [
        {
          n: "01",
          title: "تصميم مواقع",
          body: "واجهات لها موقف. نصمّم الهيكل والنوع والسلوك حتى تبدو العلامة متأنية على كل شاشة — لا تكييفاً بعد فوات الأوان.",
        },
        {
          n: "02",
          title: "تطوير مواقع",
          body: "التصميم، مبنياً كمنتج. هندسة سريعة ومتينة وقابلة للنمو — لا قالب استُبدل شعاره.",
        },
        {
          n: "03",
          title: "صفحات هبوط",
          body: "سطح واحد لمهمة واحدة. مركّزة، سريعة الفهم، ومكتوبة للتحويل — بلا زينة وبلا زيادة.",
        },
        {
          n: "04",
          title: "بعد الإطلاق",
          body: "المنتج لا يتجمّد يوم الشحن. تحديثات وتحسينات وموثوقية تُبقي التجربة حادّة مع حركة العمل.",
        },
      ],
    },
    about: {
      index: "03",
      label: "نبذة",
      name: "ALTURA",
      aside: "وكالة رقمية · ارتقاء عبر الحرفية",
      title: "ALTURA وُجدت لترتقي بطريقة معايشة العمل على الإنترنت.",
      p1: "نجمع الاستراتيجية والتصميم والهندسة والإبداع البشري. التقنية الحديثة — بما فيها الذكاء الاصطناعي — داخل سير العمل: بحثاً واستكشافاً وإنتاجاً. الغاية ليست موقعاً أعلى صوتاً. بل معيار حضور أعلى.",
      p2: "التعاون مباشر. تتحدث مع من يصنع المنتج. القرارات تبقى قريبة. العمل يُصنع ليمثّل عملاً — محلياً أو دولياً — وليساعد الناس على توظيفك أو الشراء منك.",
      p3: "نحن استوديو رشيق. لا طبقة حسابات. إذا كان العمل لنا أن نصنعه، نصنعه. ثم نبقى معه — نختبر ونُحسّن ونرفع التجربة مع نمو العمل.",
    },
    process: {
      index: "04",
      label: "العملية",
      title: "عمل يواصل الارتفاع.",
      steps: [
        {
          n: "01",
          title: "نفهم",
          body: "ندرس العمل والجمهور والقيد. نسأل عن الموجز قبل أن نلتزم به. لا يبدأ العمل دون ذلك.",
        },
        {
          n: "02",
          title: "نشكّل",
          body: "الاستراتيجية تصير مفهوماً. نوع وواجهة ونظام — حتى يبدو المنتج حتمياً، لا مجمّعاً.",
        },
        {
          n: "03",
          title: "نبني",
          body: "نهندس من أجل السرعة والوضوح والمتانة. أدوات ذكية داخل سير العمل، كي يمضي العمل أبعد من دون أن يفقد العناية.",
        },
        {
          n: "04",
          title: "نطوّر",
          body: "الإطلاق بداية. نختبر ونُحسّن ونواصل رفع المنتج مع تغيّر العمل.",
        },
      ],
    },
    why: {
      index: "05",
      label: "لماذا ALTURA",
      title: "معايير أعلى.\nتنفيذ أوضح.",
      items: [
        {
          n: "01",
          title: "من يصنع العمل.",
          body: "تعمل مع المصممين والمهندسين على المنتج. لا طبقة حسابات بينك وبين العمل.",
        },
        {
          n: "02",
          title: "نظام واحد، لا تسليم.",
          body: "التصميم والهندسة وأساليب العمل المعزّزة بالذكاء الاصطناعي تبقى في الحوار نفسه. لا شيء يُفقد بين الفكرة والبناء.",
        },
        {
          n: "03",
          title: "مبني ليعمل.",
          body: "للموقع مهمة: أن يمثّل الشركة، ويكسب الثقة، ويحوّل. نصمّم لذلك — ثم نواصل رفعه.",
        },
      ],
    },
    contact: {
      index: "06",
      label: "تواصل",
      title: "إن كان ينبغي أن يرتقي،\nابدأ هنا.",
      lead: "أخبرنا ماذا يفعل العمل، وهل يوجد موقع، وأي توقيت يهم. نقرأ كل موجز.",
      book: "اعمل مع ALTURA",
      bookNote: "أو أرسل موجزاً أدناه.",
      bookModalTitle: "حوار عمل",
      bookModalLead: "ثلاثون دقيقة. العمل، والمنتج، وما إذا كان ينبغي أن نعمل معاً.",
      bookModalCta: "راسلنا لتحديد موعد",
      bookClose: "إغلاق",
      name: "الاسم",
      email: "البريد",
      type: "من أين نبدأ؟",
      types: {
        design: "تصميم مواقع",
        development: "تطوير مواقع",
        landing: "صفحة هبوط",
        maintenance: "بعد الإطلاق",
      },
      message: "الرسالة",
      submit: "أرسل الموجز",
      sending: "جارٍ الإرسال",
      successTitle: "وصل إلينا.",
      successBody: "نقرأ كل موجز. ستصلك إجابتنا عبر البريد.",
      another: "إرسال أخرى",
      errors: {
        name: "يرجى إضافة اسمك.",
        email: "يرجى إضافة بريد صالح.",
        type: "يرجى اختيار من أين نبدأ.",
        message: "يرجى إضافة ملاحظة قصيرة عن المشروع.",
      },
    },
    footer: {
      email: "hello@altura.com",
      line: "تجارب رقمية، مرفوعة.",
    },
  },
} as const;

export type Copy = (typeof copy)[Lang];
