export const copy = {
  en: {
    skip: "Skip to content",
    scroll: "Scroll",
    language: {
      label: "Language",
      en: "EN",
      ar: "العربية",
    },
    meta: {
      title: "VARON — Digital experiences, built with intelligence",
      description:
        "VARON is a creative technology studio. We design and build websites, digital products, and AI-powered systems — strategy, design, and engineering in one studio.",
    },
    nav: {
      work: "Work",
      capabilities: "Capabilities",
      about: "About",
      contact: "Contact",
      menu: "Menu",
      close: "Close",
      book: "Book a call",
    },
    hero: {
      kicker: "Creative technology studio",
      title: "Digital experiences,\nbuilt with intelligence.",
      lead: "VARON designs and builds websites, digital products, and AI-powered systems for companies that take their work seriously. Strategy, design, and engineering — in one studio.",
      primary: "Book a 30-minute discovery call",
      secondary: "Explore our work",
      roles: ["Strategy", "Design", "Engineering", "Intelligence"],
      rolesLabel: "Disciplines",
      artifactLabel: "Abstract grid of squares — the VARON mark in motion",
    },
    intro: {
      label: "Studio",
      statement:
        "VARON combines design, engineering, and intelligent systems to create digital products that feel as good as they perform.",
      supporting:
        "We work directly with founders and teams. No account layer, no hand-offs — the people you meet are the people who make the work.",
    },
    work: {
      index: "01",
      label: "Selected work",
      title: "One engagement,\nshown in full.",
      lead: "Architecture, interface, and engineering — treated as one system, from the first brief to launch.",
      viewProject: "View project",
      metaProject: "Project",
      metaClient: "Client",
      metaCategory: "Category",
      metaScope: "Scope",
      featured: {
        id: "open",
        n: "01",
        name: "open",
        category: "Digital product & platform",
        header: "Product and platform, engineered together.",
        subheading: "A high-performance web experience, built to grow with the company.",
        story:
          "We partnered with open to turn an ambitious product vision into a complete digital platform. Architecture, interface, and engineering moved as one system — so the brand, the performance, and the product arrived together.",
        badges: ["Product Strategy", "Interface Engineering", "Full-Stack Development", "Performance Systems"],
        website: "https://www.open.cx",
        websiteLabel: "open.cx",
        video: "/work/open-re.mp4",
        poster: "/work/oben-desktop.png",
        videoAlt: "Screen recording of the open website.",
      },
    },
    testimonial: {
      label: "In their words",
      quote:
        "Working with the team was an exceptional experience. They demonstrated world-class standards in product engineering, rapid execution, and the ability to translate complex business needs into an intuitive digital product. I highly recommend them to anyone looking to build a top-tier digital product.",
      name: "Mohammad Gharabat",
      role: "Founder & CEO at open",
      initials: "MG",
      photo: "/work/mohammad-gharabat.jpg",
      linkedInLabel: "LinkedIn",
      emailLabel: "Email",
      linkedIn: "https://www.linkedin.com/in/gharabat",
      email: "mo@open.cx",
    },
    capabilities: {
      index: "02",
      label: "Capabilities",
      title: "What we make.",
      lead: "Four disciplines, one team. Most engagements draw on more than one.",
      items: [
        {
          n: "01",
          title: "Websites",
          body: "Premium websites and digital experiences designed around clarity, brand, and conversion.",
          detail: "Marketing sites, product sites, and the design systems that keep them fast and exact.",
        },
        {
          n: "02",
          title: "AI Systems",
          body: "AI-powered workflows, copilots, automation, and custom digital systems.",
          detail: "Practical intelligence, integrated where it saves time or sharpens a decision.",
        },
        {
          n: "03",
          title: "Product Design",
          body: "Digital products and interfaces designed around real users and business goals.",
          detail: "From first flows to a shipped interface — research, prototyping, and UI.",
        },
        {
          n: "04",
          title: "Brand & Digital Identity",
          body: "Distinctive identities and digital systems for ambitious companies.",
          detail: "Wordmarks, typography, and the digital system that carries them everywhere.",
        },
      ],
    },
    intelligence: {
      index: "03",
      label: "Intelligence",
      title: "Intelligent where it matters.",
      lead: "We use AI where it improves the product or the process — inside interfaces, workflows, and the way we build. Not as a headline.",
      items: [
        {
          n: "01",
          title: "Intelligent interfaces",
          body: "Search, assistance, and personalization that feel native to the product — not bolted on.",
        },
        {
          n: "02",
          title: "Automation",
          body: "Workflows that remove repetitive steps for your team and for your customers.",
        },
        {
          n: "03",
          title: "Custom systems",
          body: "Copilots and internal tools built around your data, your rules, and your constraints.",
        },
        {
          n: "04",
          title: "Data-driven workflows",
          body: "Instrumented products, so decisions are based on what people actually do.",
        },
      ],
      diagramLabel: "Animated dot matrix",
    },
    process: {
      index: "04",
      label: "Process",
      title: "From first brief\nto lasting work.",
      steps: [
        {
          n: "01",
          title: "Understand",
          body: "We study the business, the audience, and the constraint. We question the brief before we honor it. No work starts without that.",
        },
        {
          n: "02",
          title: "Shape",
          body: "Strategy becomes a concept. Type, interface, and system — until the product feels inevitable, not assembled.",
        },
        {
          n: "03",
          title: "Build",
          body: "We engineer for speed, clarity, and durability. Intelligent tools sit inside the workflow, so the work moves further without losing care.",
        },
        {
          n: "04",
          title: "Evolve",
          body: "Launch is a beginning. We test, refine, and keep the product exact as the business changes.",
        },
      ],
    },
    about: {
      index: "05",
      label: "About",
      title: "VARON exists to make digital work that holds its value.",
      p1: "VARON is a studio for digital work made with the care of a craft. We combine strategy, design, engineering, and human judgment. Intelligent tools sit inside the process — research, exploration, production — so the work is sharper, not louder.",
      p2: "The collaboration is direct. You speak with the people making the product. Decisions stay close. The work is made to represent a business — local or international — and to help people hire you or buy from you.",
      p3: "We are a lean studio. There is no account layer. If the work is ours to make, we make it. Then we stay with it — testing, refining, keeping the product exact as the business grows.",
      principlesLabel: "Principles",
      principles: [
        {
          n: "01",
          title: "The people making it.",
          body: "You work with the designers and engineers on the product. No account layer between you and the work.",
        },
        {
          n: "02",
          title: "One system, not a handoff.",
          body: "Design, engineering, and intelligent workflows stay in the same conversation. Nothing is lost between the idea and the build.",
        },
        {
          n: "03",
          title: "Built to last.",
          body: "The site has a job: represent the company, earn trust, and convert. We design for that — then keep it exact.",
        },
      ],
    },
    contact: {
      index: "06",
      label: "Contact",
      title: "Let’s build\nwhat comes next.",
      lead: "Tell us what you’re working on. Thirty minutes is enough to know whether we’re the right studio for it.",
      book: "Book a 30-minute discovery call",
      bookAria: "Book a 30-minute discovery call — opens the scheduling dialog",
      emailLabel: "Or email us",
    },
    booking: {
      label: "Discovery call",
      title: "Book a 30-minute call",
      hint: "Choose a date and time that suits you. Everything happens right here.",
      loading: "Loading the calendar",
      failed: "The calendar couldn’t load. Check your connection and try again.",
      retry: "Try again",
    },
    footer: {
      tagline: "Creative technology studio",
      navLabel: "Navigation",
      contactLabel: "Contact",
      rights: "All rights reserved.",
    },
    notFound: {
      label: "404",
      title: "This page\ndoesn’t exist.",
      lead: "The page you’re looking for may have moved, or the link may be incorrect.",
      home: "Back to home",
      documentTitle: "Page not found — VARON",
    },
  },
  ar: {
    skip: "تخطَّ إلى المحتوى",
    scroll: "تمرير",
    language: {
      label: "اللغة",
      en: "EN",
      ar: "العربية",
    },
    meta: {
      title: "VARON — تجارب رقمية، تُبنى بذكاء",
      description:
        "VARON استوديو تكنولوجيا إبداعية. نصمّم ونبني المواقع الإلكترونية والمنتجات الرقمية والأنظمة المدعومة بالذكاء الاصطناعي — استراتيجية وتصميم وهندسة في استوديو واحد.",
    },
    nav: {
      work: "الأعمال",
      capabilities: "القدرات",
      about: "عنّا",
      contact: "تواصل",
      menu: "القائمة",
      close: "إغلاق",
      book: "احجز مكالمة",
    },
    hero: {
      kicker: "استوديو تكنولوجيا إبداعية",
      title: "تجارب رقمية،\nتُبنى بذكاء.",
      lead: "تصمّم VARON وتبني المواقع الإلكترونية والمنتجات الرقمية والأنظمة المدعومة بالذكاء الاصطناعي للشركات التي تأخذ عملها بجدية. استراتيجية وتصميم وهندسة — في استوديو واحد.",
      primary: "احجز مكالمة تعارف مدتها ٣٠ دقيقة",
      secondary: "استكشف أعمالنا",
      roles: ["استراتيجية", "تصميم", "هندسة", "ذكاء"],
      rolesLabel: "التخصصات",
      artifactLabel: "شبكة مجرّدة من المربعات — علامة VARON في حركة",
    },
    intro: {
      label: "الاستوديو",
      statement:
        "تجمع VARON بين التصميم والهندسة والأنظمة الذكية لتصنع منتجات رقمية يوازي إحساسُها أداءَها.",
      supporting:
        "نعمل مباشرة مع المؤسسين والفرق. لا طبقة حسابات ولا تسليمات وسيطة — من تلتقيهم هم من يصنعون العمل.",
    },
    work: {
      index: "01",
      label: "أعمال مختارة",
      title: "شراكة واحدة،\nتُعرض كاملة.",
      lead: "المعمارية والواجهة والهندسة — تُعالَج كمنظومة واحدة، من الإحاطة الأولى حتى الإطلاق.",
      viewProject: "عرض المشروع",
      metaProject: "المشروع",
      metaClient: "العميل",
      metaCategory: "الفئة",
      metaScope: "النطاق",
      featured: {
        id: "open",
        n: "01",
        name: "open",
        category: "منتج رقمي ومنصة",
        header: "منتج ومنصة، صُمّما معًا.",
        subheading: "تجربة ويب عالية الأداء، مبنية لتنمو مع الشركة.",
        story:
          "شاركنا open لتحويل رؤية منتج طموحة إلى منصة رقمية مكتملة. تحركت المعمارية والواجهة والهندسة كمنظومة واحدة — فوصلت العلامة والأداء والمنتج معًا.",
        badges: ["استراتيجية المنتج", "هندسة الواجهة", "تطوير متكامل", "أنظمة الأداء"],
        website: "https://www.open.cx",
        websiteLabel: "open.cx",
        video: "/work/open-re.mp4",
        poster: "/work/oben-desktop.png",
        videoAlt: "تسجيل شاشة لموقع open.",
      },
    },
    testimonial: {
      label: "بكلماتهم",
      quote:
        "كان العمل مع الفريق تجربة استثنائية. أظهروا معايير عالمية في هندسة المنتج، وسرعة في التنفيذ، وقدرة على تحويل احتياجات الأعمال المعقّدة إلى منتج رقمي واضح وسهل الاستخدام. أوصي بهم لكل من يسعى إلى بناء منتج رقمي رفيع المستوى.",
      name: "محمد غرابات",
      role: "المؤسس والرئيس التنفيذي في open",
      initials: "MG",
      photo: "/work/mohammad-gharabat.jpg",
      linkedInLabel: "لينكدإن",
      emailLabel: "البريد",
      linkedIn: "https://www.linkedin.com/in/gharabat",
      email: "mo@open.cx",
    },
    capabilities: {
      index: "02",
      label: "القدرات",
      title: "ما نصنعه.",
      lead: "أربعة تخصصات، وفريق واحد. تستفيد معظم المشاريع من أكثر من تخصص.",
      items: [
        {
          n: "01",
          title: "مواقع إلكترونية",
          body: "مواقع إلكترونية وتجارب رقمية راقية، تُصمَّم حول الوضوح والعلامة والتحويل.",
          detail: "مواقع تسويقية ومواقع منتجات، وأنظمة التصميم التي تُبقيها سريعة ودقيقة.",
        },
        {
          n: "02",
          title: "أنظمة الذكاء الاصطناعي",
          body: "مسارات عمل مدعومة بالذكاء الاصطناعي، ومساعدون، وأتمتة، وأنظمة رقمية مخصّصة.",
          detail: "ذكاء عملي يُدمج حيث يوفّر الوقت أو يُحسّن القرار.",
        },
        {
          n: "03",
          title: "تصميم المنتجات",
          body: "منتجات رقمية وواجهات تُصمَّم حول المستخدمين الحقيقيين وأهداف العمل.",
          detail: "من المسارات الأولى إلى واجهة مُطلَقة — بحث ونماذج أولية وواجهات.",
        },
        {
          n: "04",
          title: "الهوية والعلامة الرقمية",
          body: "هويات مميّزة وأنظمة رقمية للشركات الطموحة.",
          detail: "علامات حرفية وطباعة، والنظام الرقمي الذي يحملها في كل مكان.",
        },
      ],
    },
    intelligence: {
      index: "03",
      label: "الذكاء",
      title: "ذكيّ حيث يهمّ.",
      lead: "نستخدم الذكاء الاصطناعي حيث يُحسّن المنتج أو العملية — داخل الواجهات ومسارات العمل وطريقة بنائنا. لا كعنوان تسويقي.",
      items: [
        {
          n: "01",
          title: "واجهات ذكية",
          body: "بحث ومساعدة وتخصيص تبدو جزءًا أصيلًا من المنتج — لا إضافة عليه.",
        },
        {
          n: "02",
          title: "الأتمتة",
          body: "مسارات عمل تُزيل الخطوات المتكررة عن فريقك وعن عملائك.",
        },
        {
          n: "03",
          title: "أنظمة مخصّصة",
          body: "مساعدون وأدوات داخلية تُبنى حول بياناتك وقواعدك وقيودك.",
        },
        {
          n: "04",
          title: "مسارات قائمة على البيانات",
          body: "منتجات مُقاسة، لتُبنى القرارات على ما يفعله الناس فعلًا.",
        },
      ],
      diagramLabel: "مصفوفة نقاط متحركة",
    },
    process: {
      index: "04",
      label: "المنهج",
      title: "من الإحاطة الأولى\nإلى عمل يدوم.",
      steps: [
        {
          n: "01",
          title: "نفهم",
          body: "ندرس النشاط والجمهور والقيد. نسائل الإحاطة قبل أن نلتزم بها. لا يبدأ العمل من دون ذلك.",
        },
        {
          n: "02",
          title: "نشكّل",
          body: "تصير الاستراتيجية مفهومًا. الحرف والواجهة والنظام — حتى يبدو المنتج حتميًا، لا مجمّعًا.",
        },
        {
          n: "03",
          title: "نبني",
          body: "نُهندس للسرعة والوضوح والمتانة. وتعمل الأدوات الذكية داخل سير العمل، فيمضي العمل أبعد من دون أن يفقد العناية.",
        },
        {
          n: "04",
          title: "نطوّر",
          body: "الإطلاق بداية. نختبر ونصقل ونُبقي المنتج دقيقًا مع تغيّر النشاط.",
        },
      ],
    },
    about: {
      index: "05",
      label: "عنّا",
      title: "وُجدت VARON لتصنع عملًا رقميًا يحتفظ بقيمته.",
      p1: "VARON استوديو للعمل الرقمي يُصنع بعناية الحرفة. نجمع الاستراتيجية والتصميم والهندسة والحكم البشري. وتعمل الأدوات الذكية داخل العملية — البحث والاستكشاف والإنتاج — فيكون العمل أحدّ، لا أعلى صوتًا.",
      p2: "التعاون مباشر. تتحدث مع من يصنع المنتج. تبقى القرارات قريبة. يُصنع العمل ليمثّل نشاطًا — محليًا أو دوليًا — وليساعد الناس على اختيارك أو الشراء منك.",
      p3: "نحن استوديو رشيق. لا طبقة حسابات بينك وبين العمل. إن كان العمل لنا، ننجزه. ثم نبقى معه — نختبر ونصقل ونُبقيه دقيقًا مع نمو النشاط.",
      principlesLabel: "المبادئ",
      principles: [
        {
          n: "01",
          title: "من يصنعه.",
          body: "تعمل مع المصممين والمهندسين على المنتج. لا طبقة حسابات بينك وبين العمل.",
        },
        {
          n: "02",
          title: "منظومة واحدة، لا تسليم.",
          body: "يبقى التصميم والهندسة ومسارات العمل الذكية في الحوار نفسه. لا يضيع شيء بين الفكرة والتنفيذ.",
        },
        {
          n: "03",
          title: "يُبنى ليدوم.",
          body: "للموقع وظيفة: أن يمثّل الشركة، ويكسب الثقة، ويحوّل. نصمّم لذلك — ثم نُبقيه دقيقًا.",
        },
      ],
    },
    contact: {
      index: "06",
      label: "تواصل",
      title: "لنبنِ\nما يأتي بعد ذلك.",
      lead: "أخبرنا بما تعمل عليه. ثلاثون دقيقة تكفي لنعرف إن كنّا الاستوديو المناسب له.",
      book: "احجز مكالمة تعارف مدتها ٣٠ دقيقة",
      bookAria: "احجز مكالمة تعارف مدتها ٣٠ دقيقة — تفتح نافذة الحجز",
      emailLabel: "أو راسلنا بالبريد",
    },
    booking: {
      label: "مكالمة تعارف",
      title: "احجز مكالمة مدتها ٣٠ دقيقة",
      hint: "اختر التاريخ والوقت المناسبين لك. كل شيء يتم هنا مباشرة.",
      loading: "جارٍ تحميل التقويم",
      failed: "تعذّر تحميل التقويم. تحقّق من اتصالك وأعد المحاولة.",
      retry: "أعد المحاولة",
    },
    footer: {
      tagline: "استوديو تكنولوجيا إبداعية",
      navLabel: "التنقل",
      contactLabel: "تواصل",
      rights: "جميع الحقوق محفوظة.",
    },
    notFound: {
      label: "404",
      title: "هذه الصفحة\nغير موجودة.",
      lead: "قد تكون الصفحة التي تبحث عنها قد انتقلت، أو أن الرابط غير صحيح.",
      home: "العودة إلى الصفحة الرئيسية",
      documentTitle: "الصفحة غير موجودة — VARON",
    },
  },
} as const;

export type Lang = keyof typeof copy;
export type Copy = (typeof copy)[Lang];
