export type Lang = "en" | "ar";
export type ProjectType = "design" | "development" | "landing" | "maintenance";

export const copy = {
  en: {
    skip: "Skip to content",
    scroll: "Scroll",
    nav: {
      work: "Work",
      services: "Services",
      about: "About",
      contact: "Contact",
      menu: "Menu",
      close: "Close",
    },
    hero: {
      kicker: "Digital product & web agency",
      title: "By pixel",
      line: "Websites and digital experiences\nbuilt to scale your business.",
      lead: "We design and engineer high-performance websites and digital products. Clean code, bespoke design, and seamless execution.",
      primary: "Start a project",
      secondary: "Selected work",
      roles: ["Web Design", "Web Development", "Landing Pages", "Website Maintenance"],
    },
    work: {
      index: "01",
      label: "Selected work",
      title: "A platform built\nto scale.",
      lead: "Featured engagement — product architecture, interface, and engineering, shipped as one.",
      visit: "Visit live platform",
      featured: {
        id: "oben",
        name: "Oben",
        category: "Digital product & platform",
        header: "Oben — End-to-End Digital Product & Platform Engineering",
        subheading: "Architecting a high-performance, scalable web experience built for growth.",
        story:
          "We partnered with Oben to build and launch a complete digital platform aligned with their grand vision. Our team led the product architecture, UI/UX strategy, and full-stack development—delivering a blazing-fast, responsive interface engineered to elevate their brand and deliver seamless user engagement.",
        badges: [
          "Product Strategy",
          "UI/UX Engineering",
          "Full-Stack Development",
          "Performance Optimization",
        ],
        website: "https://www.open.cx",
        websiteLabel: "open.cx",
        video: "/work/oben-walkthrough.mp4",
        poster: "/work/oben-desktop.png",
        videoAlt: "Screen recording of the Oben website in a browser frame.",
      },
      testimonial: {
        quote:
          "Working with the team was an exceptional experience. They demonstrated world-class standards in product engineering, rapid execution, and the ability to translate complex business needs into an intuitive digital product. I highly recommend them to anyone looking to build a top-tier digital product.",
        name: "Mohammad Gharabat",
        role: "Founder & CEO at Oben",
        initials: "MG",
        photo: "/work/mohammad-gharabat.jpg",
        contact: "Contact Founder for Reference",
        linkedInLabel: "LinkedIn",
        emailLabel: "Email",
        linkedIn: "https://www.linkedin.com/in/gharabat",
        email: "mo@open.cx",
      },
    },
    services: {
      index: "02",
      label: "Services",
      title: "What we take on.",
      items: [
        {
          n: "01",
          title: "Web Design",
          body: "Structure, type, and pages for a business that needs the site to feel considered before anything is built.",
        },
        {
          n: "02",
          title: "Web Development",
          body: "A designed direction, built properly. Fast, maintainable, and made to last — not a theme with the logo swapped.",
        },
        {
          n: "03",
          title: "Landing Pages",
          body: "A focused page for a specific offer. Clear, fast, and written to convert — without extra sections for their own sake.",
        },
        {
          n: "04",
          title: "Website Maintenance",
          body: "Care after launch. Updates, refinements, and keeping the site reliable so it does not drift.",
        },
      ],
    },
    about: {
      index: "03",
      label: "About",
      name: "Pixel",
      aside: "Digital studio · Design + engineering",
      title: "At Pixel, we build custom websites for businesses that demand a distinct digital presence—no slow templates or generic layouts.",
      p1: "We think in pages and in code at the same time. Design and engineering stay coherent — nothing is lost between a file and a build.",
      p2: "The work is direct. You speak with the people making the product. Decisions stay close. The site is made to represent a business — local or international — and to help people hire you or buy from you.",
      p3: "We are a lean studio. There is no account layer. If the work is ours to make, we make it.",
    },
    process: {
      index: "04",
      label: "Process",
      title: "Four movements.",
      steps: [
        {
          n: "01",
          title: "Discover",
          body: "We analyze your business and audience, and what the site has to do. No work starts without that.",
        },
        {
          n: "02",
          title: "Design",
          body: "We craft tailored design systems, type, and pages — until the site feels like you, not like a layout anyone could have bought.",
        },
        {
          n: "03",
          title: "Develop",
          body: "We develop clean, high-performance code from that direction, with the same attention. The site becomes a working product.",
        },
        {
          n: "04",
          title: "Launch",
          body: "We test, launch, and ensure your team is equipped for growth.",
        },
      ],
    },
    why: {
      index: "05",
      label: "Why Pixel",
      title: "Precision Design.\nEngineering Excellence.",
      items: [
        {
          n: "01",
          title: "Direct senior collaboration.",
          body: "You work directly with the designers and developers creating your product.",
        },
        {
          n: "02",
          title: "Design & code in sync.",
          body: "We bridge the gap between aesthetics and performance so your site looks great and runs fast.",
        },
        {
          n: "03",
          title: "Built for growth.",
          body: "Every pixel and line of code is optimized to help you convert visitors into clients.",
        },
      ],
    },
    contact: {
      index: "06",
      label: "Contact",
      title: "Let's build\nsomething remarkable.",
      lead: "Tell us what the business does, whether a site exists, and any timing that matters. We read every message.",
      book: "Book a Discovery Call",
      bookNote: "Or send a brief below.",
      bookModalTitle: "Discovery call",
      bookModalLead: "Thirty minutes. We cover the business, the product, and whether the work is a fit.",
      bookModalCta: "Email to schedule",
      bookClose: "Close",
      name: "Name",
      email: "Email",
      type: "What you need",
      types: {
        design: "Web design",
        development: "Web development",
        landing: "Landing page",
        maintenance: "Maintenance",
      },
      message: "Message",
      submit: "Send",
      sending: "Sending",
      successTitle: "Received.",
      successBody: "We read every note. We will reply by email.",
      another: "Send another",
      errors: {
        name: "Please add your name.",
        email: "Please add a valid email.",
        type: "Please choose what you need.",
        message: "Please add a short note about the project.",
      },
    },
    footer: {
      email: "hello@bypixel.com",
      line: "Digital web agency & product development",
    },
  },
  ar: {
    skip: "تخطي إلى المحتوى",
    scroll: "تمرير",
    nav: {
      work: "الأعمال",
      services: "الخدمات",
      about: "نبذة",
      contact: "تواصل",
      menu: "القائمة",
      close: "إغلاق",
    },
    hero: {
      kicker: "وكالة رقمية وتطوير منتجات",
      title: "By pixel",
      line: "مواقع وتجارب رقمية\nتُبنى لتوسيع أعمالك.",
      lead: "نصمّم ونهندس مواقع ومنتجات رقمية عالية الأداء. شيفرة نظيفة، تصميم مخصّص، وتنفيذ سلس.",
      primary: "ابدأ مشروعاً",
      secondary: "أعمال مختارة",
      roles: ["تصميم مواقع", "تطوير مواقع", "صفحات هبوط", "صيانة مواقع"],
    },
    work: {
      index: "01",
      label: "أعمال مختارة",
      title: "منصة تُبنى\nلتتسع.",
      lead: "عمل مختار — هندسة المنتج والواجهة والتطوير، كمنجز واحد.",
      visit: "زيارة المنصة",
      featured: {
        id: "oben",
        name: "أوبن",
        category: "منتج رقمي ومنصة",
        header: "أوبن — هندسة منتج رقمي ومنصة من البداية إلى النهاية",
        subheading: "تجربة ويب عالية الأداء وقابلة للتوسع، مبنية للنمو.",
        story:
          "شاركنا أوبن في بناء وإطلاق منصة رقمية مكتملة تتوافق مع رؤيتهم. قاد فريقنا هندسة المنتج واستراتيجية الواجهة والتجربة والتطوير الكامل — بواجهة سريعة ومتجاوبة صُمّمت لترتقي بالعلامة وتقدّم تفاعلاً سلساً.",
        badges: ["استراتيجية المنتج", "هندسة الواجهة والتجربة", "تطوير كامل", "تحسين الأداء"],
        website: "https://www.open.cx",
        websiteLabel: "open.cx",
        video: "/work/oben-walkthrough.mp4",
        poster: "/work/oben-desktop.png",
        videoAlt: "تسجيل لشاشة موقع أوبن داخل إطار متصفح.",
      },
      testimonial: {
        quote:
          "العمل مع الفريق كان تجربة استثنائية. أظهروا معايير عالمية في هندسة المنتج، وتنفيذاً سريعاً، وقدرة على تحويل احتياجات العمل المعقّدة إلى منتج رقمي بديهي. أوصي بهم بقوة لكل من يريد بناء منتج رقمي من الطراز الأول.",
        name: "محمد غرابات",
        role: "مؤسس والرئيس التنفيذي في أوبن",
        initials: "مغ",
        photo: "/work/mohammad-gharabat.jpg",
        contact: "تواصل مع المؤسس للمرجع",
        linkedInLabel: "لينكدإن",
        emailLabel: "البريد",
        linkedIn: "https://www.linkedin.com/in/gharabat",
        email: "mo@open.cx",
      },
    },
    services: {
      index: "02",
      label: "خدمات",
      title: "ما نتولاه.",
      items: [
        {
          n: "01",
          title: "تصميم مواقع",
          body: "هيكل ونوع وصفحات لأعمال تحتاج أن يبدو الموقع متأنياً قبل أي بناء.",
        },
        {
          n: "02",
          title: "تطوير مواقع",
          body: "اتجاه مصمّم، يُبنى بشكل سليم. سريع وقابل للصيانة ويدوم — لا قالب استُبدل شعاره.",
        },
        {
          n: "03",
          title: "صفحات هبوط",
          body: "صفحة مركّزة لعرض محدد. واضحة وسريعة ومكتوبة للتحويل — بلا أقسام زائدة.",
        },
        {
          n: "04",
          title: "صيانة مواقع",
          body: "عناية بعد الإطلاق. تحديثات وتحسينات، وإبقاء الموقع موثوقاً فلا ينجرف.",
        },
      ],
    },
    about: {
      index: "03",
      label: "نبذة",
      name: "Pixel",
      aside: "استوديو رقمي · تصميم وهندسة",
      title: "في Pixel، نبني مواقع مخصّصة لأعمال تطلب حضوراً رقمياً مميزاً — لا قوالب بطيئة ولا تخطيطات عامة.",
      p1: "نفكّر في الصفحات وفي الشيفرة في الوقت نفسه. التصميم والهندسة يبقيان متماسكين — ولا شيء يُفقد بين ملف وبناء.",
      p2: "العمل مباشر. تتحدث مع من يصنع المنتج. القرارات تبقى قريبة. الموقع يُصنع ليمثّل عملاً — محلياً أو دولياً — وليساعد الناس على توظيفك أو الشراء منك.",
      p3: "نحن استوديو رشيق. لا طبقة حسابات. إذا كان العمل لنا أن نصنعه، نصنعه.",
    },
    process: {
      index: "04",
      label: "العملية",
      title: "أربع حركات.",
      steps: [
        {
          n: "01",
          title: "تعرّف",
          body: "نحلّل عملك وجمهورك، وما على الموقع أن يفعله. لا يبدأ العمل دون ذلك.",
        },
        {
          n: "02",
          title: "تصميم",
          body: "نصمّم أنظمة تصميم مخصّصة، ونوعاً وصفحات — حتى يبدو الموقع مثلك، لا كتخطيط يمكن لأي أحد شراءه.",
        },
        {
          n: "03",
          title: "تطوير",
          body: "نطوّر شيفرة نظيفة عالية الأداء من ذلك الاتجاه، بنفس العناية. يصير الموقع منتجاً يعمل.",
        },
        {
          n: "04",
          title: "إطلاق",
          body: "نختبر ونطلق ونتأكد أن فريقك جاهز للنمو.",
        },
      ],
    },
    why: {
      index: "05",
      label: "لماذا Pixel",
      title: "تصميم دقيق.\nتميّز هندسي.",
      items: [
        {
          n: "01",
          title: "تعاون مباشر مع الفريق الأقدم.",
          body: "تعمل مباشرة مع المصممين والمطوّرين الذين يصنعون منتجك.",
        },
        {
          n: "02",
          title: "التصميم والشيفرة معاً.",
          body: "نسد الفجوة بين الجمال والأداء كي يبدو الموقع رائعاً ويعمل بسرعة.",
        },
        {
          n: "03",
          title: "مبني للنمو.",
          body: "كل بكسل وكل سطر شيفرة مُحسَّن ليحوّل الزوار إلى عملاء.",
        },
      ],
    },
    contact: {
      index: "06",
      label: "تواصل",
      title: "لنبنِ شيئاً\nيستحق الذكر.",
      lead: "أخبرنا ماذا يفعل العمل، وهل يوجد موقع، وأي توقيت يهم. نقرأ كل رسالة.",
      book: "احجز مكالمة تعارف",
      bookNote: "أو أرسل موجزاً أدناه.",
      bookModalTitle: "مكالمة تعارف",
      bookModalLead: "ثلاثون دقيقة. نتحدث عن العمل، والمنتج، وما إذا كان المشروع مناسباً.",
      bookModalCta: "راسلنا لتحديد موعد",
      bookClose: "إغلاق",
      name: "الاسم",
      email: "البريد",
      type: "ما تحتاجه",
      types: {
        design: "تصميم مواقع",
        development: "تطوير مواقع",
        landing: "صفحة هبوط",
        maintenance: "صيانة",
      },
      message: "الرسالة",
      submit: "إرسال",
      sending: "جارٍ الإرسال",
      successTitle: "وصلت.",
      successBody: "نقرأ كل ملاحظة. سنرد عبر البريد.",
      another: "إرسال أخرى",
      errors: {
        name: "يرجى إضافة اسمك.",
        email: "يرجى إضافة بريد صالح.",
        type: "يرجى اختيار ما تحتاجه.",
        message: "يرجى إضافة ملاحظة قصيرة عن المشروع.",
      },
    },
    footer: {
      email: "hello@bypixel.com",
      line: "وكالة رقمية وتطوير منتجات",
    },
  },
} as const;

export type Copy = (typeof copy)[Lang];
